[package]
name = "osciemu"
version = "0.1.0"
authors = ["Surma <surma@surma.link>"]

[[example]]
name = "osciwasm"
path = "src/lib.rs"
crate-type = ["cdylib"]

[dependencies]
clap = "2.20.3"
byteorder = "1.2.1"
