[package]
name = "osciemu"
version = "0.1.0"
authors = ["Surma <surma@surma.link>"]

[lib]
# Uncomment the next line when building for wasm
# Cargo currently doesn’t allow target-specific options
#crate-type = ["cdylib"]

[dependencies]
clap = "2.20.3"
byteorder = "1.2.1"
